name: deconv
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.8
  - pip
  - flask
  - tqdm
  - pyyaml
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - matplotlib
  - seaborn
  - scanpy