# Pipeline parameters

ref_file: "data/xin/sc.tsv"
ref_annot_file: "data/xin/pdata.tsv"
bulk_file: "data/xin/bulk.tsv"

# Cell-type label identifying column in pheno data table
label_key: "cellType"
# Index identifying barcode column in pheno data table
index_col: 0
# Selected cell types, if empty, all cell types found in scRNA-seq are selected
selected_ct:
  - "alpha"
  - "beta"
  - "gamma"
  - "delta"

use_sub_type: False

# -------------------------------------------- #
# Preprocessing

# QC filtering
min_genes: 200
min_cells: 3

# Layer in adata.layers to use for deconvolution ("ncounts" - normalized mRNA counts, "counts" - raw mRNA counts)
layer: "ncounts"

# Normalization (-1 = None)
target_sum: -1
exclude_highly_expressed: True


# Gene weights
weight_type: "abs_score"
weight_agg: "min"
weight_quantiles: [0, 1]

# -------------------------------------------- #
# Outlier gene filtering

# min, max, mean (min best)
dropout_factor_quantile: 0.9
pseudobulk_lims: [-10, 10]
signature_quantiles: [0, 1]

# -------------------------------------------- #

# Optimization

lr: 0.01
epochs: 5000

# -------------------------------------------- #
# Output

# png, pdf
fig_fmt: "png"