package:
    name: deconv
    version: 0.9.3

source:
    path: ..

build:
    noarch: python
    script: pip install --no-deps .
  
requirements:
    build:
        - python
        - setuptools
    run:
        - python>=3.10
        - numpy>=2
        - pandas>=2.2.2
        - pyyaml
        - ipykernel
        - tqdm
        - wheel
        - pytorch-gpu
        - torchvision
        - torchaudio
        - scipy
        - matplotlib
        - matplotlib-inline
        - anndata
        - scanpy
        - numba
        - pyro-ppl
        - leidenalg
        - plotly
        - python-kaleido
        - nbformat

about:
    home: https://github.com/lutrarutra/deconv
    license: MIT
    summary: "Bulk RNA-seq Cell Type Proportion Deconvolution."