package:
    name: deconv
    version: 0.9.1

source:
    path: ..

build:
    noarch: python
    script: pip install .
  
requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy>=2
        - pandas>=2.2.2
        - ipykernel
        - tqdm
        - wheel
        - pytorch::pytorch
        - pytorch::torchvision
        - pytorch::torchaudio
        - scipy
        - matplotlib
        - matplotlib-inline
        - anndata
        - scanpy
        - numba
        - pyro-ppl
        - leidenalg
        - plotly
        - python-kaleido
        - nbformat

about:
    home: https://github.com/lutrarutra/deconv
    license: MIT
    summary: "Bulk RNA-seq Cell Type Proportion Deconvolution."